### ISSUE TITLE
Recommended changes after thesis research

### ISSUE THREAD

**Issue by MathildeTans** [OHDSI/IterativeHardThresholding#1]
I would like to propose some changes after I have experimented with IHT for my master's thesis. I have tried to commit the changes to another branch, but this failed (I didn't seem to have access).

The most important change is the default value for the initialRidgeVariance (Prior.R, line 53). This is set to be 1E4. This caused an inability to converge for my PLP model. I recommend changing it to 1E-1. 

Secondly, the todo's for step-halving can be removed. It did not produce any desirable effects. 

Lastly, in my thesis, I changed the prior type for the IHT starting prior to "laplace" (Prior.R, line 209). The default value for the initialRidgeVariance was determined with this prior type (instead of "normal"). Naturally, this means that it is not the ridge variance (but that is just a name and doesn't matter as much), but it might also mean that another default value is better when the starting prior is "normal". Whether others want to continue using "laplace" or "normal" is up to them. I used "laplace" as I read in the literature that some IHT like algorithms were initiated with Lasso, but just "normal" could also be interesting.

**Comment by msuchard** [comment]
Initial ridge variance has now been changed (bf2453f347f68e157f575fd879b13ed6c2fdccab).

I am leaving the `TODO`s because I have no evidence about the effects of step-halving and may implement someday.

The default prior choice should be `normal` as `laplace` leads to greedy starting point for iterative hard thresholding and (I believe) removes the global convergence guarantees.
